services:
  mysql:
      image: 'mysql:latest'
      container_name: mysql
      environment:
        - MYSQL_DATABASE=nova-tools
        - MYSQL_USER=nova
        - MYSQL_PASSWORD=nova
        - MYSQL_ROOT_PASSWORD=nova
      ports:
        - '3306:3306'
      volumes:
        - ./data:/var/lib/mysql
  pontainer:
    image: 'portainer/portainer-ce:alpine'
    container_name: pontainer
    ports:
      - '9000:9000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always